[project]
name = "image-generation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.2.1",
    "black>=24.10.0",
    "diffusers>=0.32.1",
    "flake8>=7.1.1",
    "huggingface-hub>=0.27.0",
    "isort>=5.13.2",
    "mypy>=1.14.0",
    "numpy>=2.2.1",
    "pre-commit>=4.0.1",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
    "tqdm>=4.67.1",
    "transformers>=4.47.1",
    "zipp>=3.21.0",
]
